version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" 
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/.env:/app/.env
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
  