apiVersion: v1 
kind: PersistentVolume
metadata:
  name: exp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: exp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

