apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'myapp'
        static_configs:
          - targets: ['myapp:3000']  
      
      - job_name: 'mongo'
        static_configs:
          - targets: ['mongo:27017']  
      
      - job_name: 'server'
        static_configs:
          - targets: ['server:4000']  

