apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myexpreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: backendrepliset-cont
          image: tharunika21/exp-back:v1.0
          ports:
            - containerPort: 4000