apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myexpreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: frontendrepliset-cont
          image: tharunika21/exp-front:v1.0
          ports:
            - containerPort: 3000
