apiVersion: v1
kind: PersistentVolume
metadata:
  name: exp-pv
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/temp/data"
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain